# Generated by Django 2.2.7 on 2019-11-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wars',
            new_name='War',
        ),
    ]
