# Generated by Django 2.2.7 on 2019-11-07 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0003_auto_20191107_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='key_technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
